Bugfix/ab#126 navbar active link
Brixel/Singer pull request #103
Opened 2019-11-19 14:19 UTC by Joren-Thijs

AB#126 Fixed Navbar issue where active link was not properly set
- Navbar uses router URL now.
- Formatted code.

2019-11-20 00:41 UTC, vyruz1986 requested changes
There are some formatting changes in here which get changed back if I save the file in my VSCode (through Prettier).
Please correct formatting using the checked in prettier config, easiest way to save all files which have changed again with the correct config loaded (open singer workspace in VSCode)

2019-11-20 15:01 UTC, BerendWouters approved these changes

2019-11-20 15:01 UTC, BerendWouters commented on Singer.API/ClientApp/src/app/modules/core/components/nav-menu/nav-menu.component.html
> +            [active]="routerLink.routerLink == router.url">
Nice fix.

2019-11-21 08:20 UTC, vyruz1986 approved these changes

2019-11-21 08:36 UTC, merged