Feature/ab#28 admin register registration
Brixel/Singer pull request #88
Opened 2019-11-07 13:12 UTC by BerendWouters

2019-11-07 20:06 UTC, vyruz1986 requested changes

2019-11-07 20:06 UTC, vyruz1986 commented on Singer.API/ClientApp/src/app/material.module.ts
> +      MatButtonToggleModule,
This module is exported but not imported...
how?

2019-11-07 20:06 UTC, vyruz1986 commented on Singer.API/ClientApp/src/app/modules/admin/components/singerevents/singer-event-registrations/singer-event-registrations.component.html
> +               <!-- <span>
Was it intentional to leave it here?

2019-11-07 20:06 UTC, vyruz1986 commented on Singer.API/ClientApp/src/app/modules/admin/components/singerevents/singer-event-registrations/singer-event-registrations.component.ts
> +      // this.singerEventService.getEventRegistrations(this.event.id).subscribe((events) => {
Remove it please

2019-11-07 20:06 UTC, vyruz1986 commented on Singer.API/ClientApp/src/app/modules/admin/components/singerevents/singer-event-registrations/singer-event-registrations.component.ts
> +      // this.singerEventService.updateRegistrants(this.event.id, registrantIds).subscribe((res) => res);
This call saves the registrants, should be uncommented?

2019-11-07 20:06 UTC, vyruz1986 commented on Singer.API/ClientApp/src/app/modules/admin/components/singerevents/singer-event-registrations/singer-event-registrations.component.ts
> +         // const registrant = new Registrant(careUser, RegistrationStatus.Pending);
Moar comments, why all the comments?

2019-11-07 20:06 UTC, vyruz1986 commented on Singer.API/ClientApp/src/app/modules/admin/components/singerevents/singer-eventadmin-register/singer-eventadmin-register.component.ts
> +      // this.singerEventService.updateRegistrants(this.event.id, registrantIds).subscribe((res) => res);
Should we not save it?

2019-11-07 20:06 UTC, vyruz1986 commented on Singer.API/ClientApp/src/app/modules/admin/components/singerevents/singer-eventadmin-register/singer-eventadmin-register.component.ts
> +      // if (!this.registrants.map(r => r.careUserId).includes(careUser.id)) {
Again, this will not be saved :(

2019-11-07 20:06 UTC, vyruz1986 commented on Singer.API/ClientApp/src/app/modules/admin/components/singerevents/singerevent-overview/singerevent-overview.component.html
> +      <ng-container matColumnDef="actions">
me like 👍

2019-11-07 20:16 UTC, vyruz1986 commented on Singer.API/ClientApp/src/app/modules/core/models/event-registration.model.ts
> +   pendingStatussesRemaining: number;
`Statusses` should be `States`

2019-11-07 20:18 UTC, BerendWouters commented on Singer.API/ClientApp/src/app/material.module.ts
> +      MatButtonToggleModule,
Will add it to the import

2019-11-07 20:21 UTC, BerendWouters commented on Singer.API/ClientApp/src/app/modules/admin/components/singerevents/singer-event-registrations/singer-event-registrations.component.html
> +               <!-- <span>
Well, not really. It was the start of the view registrations component

2019-11-07 20:29 UTC, vyruz1986 requested changes
Overall comment:
`SingleRegistrationsComponent` should be
`SingleRegistrationComponent`

2019-11-07 20:29 UTC, vyruz1986 commented on Singer.API/ClientApp/src/app/modules/shared/components/event-registration/event-registration.component.ts
> +      private _snackbar: MatSnackBar
I followed the Material naming scheme when specifying `snackBar`...
meh

2019-11-07 20:29 UTC, vyruz1986 commented on Singer.API/DTOs/Users/UserDTO.cs
> +      //[EmailAddress]
R U undoing ~god's~ wim's work?

2019-11-07 20:39 UTC, vyruz1986 requested changes
General wording remarks:
`Status` --> `State`
`Statuses` --> `States`
`Statusses` --> `States`

2019-11-07 20:39 UTC, vyruz1986 commented on Singer.API/Services/EventRegistrationService.cs
> +         var registrationStatuses = await Context.EventRegistrations
`Statuses` is not correct at all :), should be `States`

2019-11-07 20:39 UTC, vyruz1986 commented on Singer.API/Services/EventRegistrationService.cs
> +            var pendingStatusesRemaining = registrationStatuses.Count(x => x.Status == RegistrationStatus.Pending);
Again with the statuses

2019-11-07 20:52 UTC, BerendWouters commented on Singer.API/DTOs/Users/UserDTO.cs
> +      //[EmailAddress]
Yes, for now.

2019-11-07 22:24 UTC, vyruz1986 approved these changes

2019-11-07 22:47 UTC, vyruz1986 requested changes
Registering users with inappropriate age groups from the admin events page is possible.
This should be prevented with a user-friendly error message, as is done in the dashboard component

2019-11-11 21:03 UTC, vyruz1986 requested changes
Found 2 issues during testing:

1. Selecting a user who is in the correct age group, results in an exception and 500 error in the API. The UI breaks without providing feedback to indicate that the user is of an inappropriate age group
2. The 'Manage registrations' button does not work in this PR, yet it is there, wouldn't it be better to remove it or provide textual feedback that this feature is not yet functioning?

2019-11-11 21:58 UTC, vyruz1986 approved these changes

2019-11-11 21:58 UTC, merged